import { React, useEffect, useState } from "react";
import { get, post } from "../../utilities";
import { Link } from "react-router-dom";
import "./PhotoPopup.css";
import CommentsBlock from "./CommentsBlock.jsx";
import { NewComment } from "./NewPostInput.jsx";
import "./CommentSection.css";

const CommentSection = (props) => {
  const [comments, setComments] = useState([]);

  const comment1 = {
    creator_id: "12344",
    creator_name: "Bob Bob",
    parent: String(props._id), // links to the _id of a parent picture (_id is an autogenerated field by Mongoose).
    content: "hi this is a comment",
  };
  useEffect(() => {
    get("/api/comment", { parent: props._id }).then((comments) => {
      setComments(comments.concat(comment1));
    });
  }, []);

  const addNewComment = (commentObj) => {
    setComments(comments.concat([commentObj]));
  };

  return (
    <div className="instagram-comments-container">
      <div className="comments-section">
        <CommentsBlock
          picture={props.picture}
          comments={comments}
          creator_id={props.creator_id}
          userId={props.userId}
          addNewComment={addNewComment}
        />
      </div>
      <div className="new-comment-section">
        <NewComment addNewComment={addNewComment} />
      </div>
    </div>
  );
};

export default CommentSection;
