import { React, useEffect, useState } from "react";
import "./PhotoPopup.css";
import CommentsBlock from "./CommentsBlock.jsx";
import { NewComment } from "./NewPostInput.jsx";
import CommentSection from "./CommentSection.jsx";

const PhotoPopup = (props) => {
  const [comments, setComments] = useState([]);

  const comment1 = {
    creator_id: "12344",
    creator_name: "Bob Bob",
    parent: String(props._id), // links to the _id of a parent picture (_id is an autogenerated field by Mongoose).
    content: "hi this is a comment",
  };
  useEffect(() => {
    get("/api/comment", { parent: props._id }).then((comments) => {
      setComments(comments.concat(comment1));
    });
  }, []);

  const addNewComment = (commentObj) => {
    setComments(comments.concat([commentObj]));
  };

  return (
    <>
      <div className="modal" onClick={props.closeModal}>
        <div className="modal-content" onClick={(e) => e.stopPropagation()}>
          <button className="close-btn" onClick={props.closeModal}>
            x
          </button>
          <div className="modal-image-container">
            <img src={props.link} className="full-image" />
          </div>
          <CommentSection props={props} />
        </div>
      </div>
      <div>{console.log("Comments:", comments)}</div>
    </>
  );
};

export default PhotoPopup;
